
query getPosts($limit: Int = 10) {
  posts(first: $limit) {
    nodes {
      title
      date
      excerpt
      uri
      featuredImage {
        node {
          sourceUrl
        }
      }
    }
  }
}