query Posts($limit: Int = 10) {
  posts(first: $limit) {
    nodes {
      title
      date
      excerpt
      uri
      featuredImage {
        node {
          sourceUrl
        }
      }
    }
  }
}

query PostByUri($uri: String!) {
  nodeByUri(uri: $uri) {
    ... on Post {
      id
      title
      date
      content
      blocks
    }
    ... on Page {
      id
      title
      date
      content
      blocks
    }
  }
}
