fragment Post on Post {
  ...ContentNode
  ...NodeWithFeaturedImage
  content
  editorBlocks {
    name
    ...CoreGallery
    ...CoreImage
    ...CoreParagraph
    ...CoreQuote
    ...EditorBlock
  }
}